spring:
  application:
    name: intelliatech-books
  profiles:
    default: sandbox
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8080
  shutdown: graceful

app:
  request-timeout-seconds: 15
  storage:
    s3:
      region: ap-south-1
      key-prefix: intelliatech-books

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.flywaydb: INFO
