CREATE TABLE asset_categories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    category_code VARCHAR(24) NOT NULL,
    category_name VARCHAR(120) NOT NULL,
    description TEXT,
    default_depreciation_method VARCHAR(32) NOT NULL DEFAULT 'STRAIGHT_LINE',
    useful_life_years INT NOT NULL DEFAULT 3,
    residual_value_percentage DECIMAL(7,4) NOT NULL DEFAULT 0,
    depreciation_frequency VARCHAR(24) NOT NULL DEFAULT 'MONTHLY',
    default_asset_condition VARCHAR(24) NOT NULL DEFAULT 'GOOD',
    display_color VARCHAR(16) NOT NULL DEFAULT '#ef1f2c',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    notes TEXT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_asset_category_code UNIQUE (organization_id, category_code),
    CONSTRAINT uk_asset_category_name UNIQUE (organization_id, category_name),
    INDEX idx_asset_category_status (organization_id, status, deleted)
);

CREATE TABLE assets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    asset_number VARCHAR(48) NOT NULL,
    asset_name VARCHAR(180) NOT NULL,
    category_id BIGINT NOT NULL,
    sub_category VARCHAR(120),
    asset_type VARCHAR(24) NOT NULL DEFAULT 'TANGIBLE',
    brand VARCHAR(100),
    model VARCHAR(100),
    serial_number VARCHAR(120),
    barcode VARCHAR(120),
    quantity DECIMAL(14,3) NOT NULL DEFAULT 1,
    unit VARCHAR(32),
    asset_condition VARCHAR(24) NOT NULL DEFAULT 'GOOD',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    vendor_id BIGINT,
    vendor_name VARCHAR(180),
    purchase_date DATE,
    invoice_number VARCHAR(100),
    po_number VARCHAR(100),
    purchase_value DECIMAL(18,2) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(64),
    warranty_expiry DATE,
    location_name VARCHAR(120),
    department_name VARCHAR(120),
    floor_room VARCHAR(120),
    cost_center VARCHAR(120),
    assigned_resource_id BIGINT,
    assigned_resource_name VARCHAR(180),
    ownership_type VARCHAR(24) NOT NULL DEFAULT 'OWNED',
    lease_start_date DATE,
    lease_end_date DATE,
    manufacturer VARCHAR(120),
    manufacture_year INT,
    country_of_origin VARCHAR(100),
    hsn_sac_code VARCHAR(32),
    useful_life_months INT,
    notes TEXT,
    depreciation_method VARCHAR(32),
    depreciation_start_date DATE,
    depreciation_frequency VARCHAR(24),
    residual_value DECIMAL(18,2) NOT NULL DEFAULT 0,
    scrap_value DECIMAL(18,2) NOT NULL DEFAULT 0,
    capitalization_date DATE,
    current_value DECIMAL(18,2) NOT NULL DEFAULT 0,
    accumulated_depreciation DECIMAL(18,2) NOT NULL DEFAULT 0,
    net_book_value DECIMAL(18,2) NOT NULL DEFAULT 0,
    image_url VARCHAR(1000),
    is_draft BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_asset_number UNIQUE (organization_id, asset_number),
    CONSTRAINT fk_asset_category FOREIGN KEY (category_id) REFERENCES asset_categories(id),
    CONSTRAINT fk_asset_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id),
    INDEX idx_asset_search (organization_id, status, category_id, deleted),
    INDEX idx_asset_purchase_date (organization_id, purchase_date),
    INDEX idx_asset_assignment (organization_id, assigned_resource_id, status),
    INDEX idx_asset_serial (organization_id, serial_number)
);

CREATE TABLE asset_attachments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(1000) NOT NULL,
    content_type VARCHAR(100),
    file_size BIGINT,
    attachment_type VARCHAR(40) NOT NULL DEFAULT 'ASSET',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_asset_attachment_asset FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
    INDEX idx_asset_attachment (asset_id, attachment_type)
);

CREATE TABLE asset_assignments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    asset_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    resource_name VARCHAR(180) NOT NULL,
    resource_email VARCHAR(180),
    assignment_date DATE NOT NULL,
    expected_return_date DATE,
    actual_return_date DATE,
    purpose TEXT,
    cost_center VARCHAR(120),
    project_name VARCHAR(180),
    reference_number VARCHAR(100),
    notes TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    created_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_asset_assignment_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    INDEX idx_assignment_asset_active (organization_id, asset_id, status),
    INDEX idx_assignment_resource (organization_id, resource_id, status)
);

CREATE TABLE asset_maintenance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    work_order_number VARCHAR(48) NOT NULL,
    asset_id BIGINT NOT NULL,
    maintenance_type VARCHAR(64) NOT NULL,
    description TEXT NOT NULL,
    checklist_json LONGTEXT,
    technician_resource_id BIGINT,
    technician_name VARCHAR(180),
    assistant_resource_id BIGINT,
    assistant_name VARCHAR(180),
    scheduled_date DATE NOT NULL,
    due_date DATE NOT NULL,
    completed_date DATE,
    estimated_duration_hours DECIMAL(10,2),
    actual_duration_hours DECIMAL(10,2),
    estimated_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
    actual_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
    parts_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
    labour_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
    repeat_frequency VARCHAR(32) NOT NULL DEFAULT 'NONE',
    next_due_date DATE,
    priority VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    notes TEXT,
    attachment_name VARCHAR(255),
    attachment_url VARCHAR(1000),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_maintenance_number UNIQUE (organization_id, work_order_number),
    CONSTRAINT fk_maintenance_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    INDEX idx_maintenance_due (organization_id, status, due_date, deleted),
    INDEX idx_maintenance_asset (asset_id, scheduled_date)
);

CREATE TABLE asset_depreciation_schedules (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    asset_id BIGINT NOT NULL,
    method VARCHAR(32) NOT NULL,
    financial_year VARCHAR(16) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    frequency VARCHAR(24) NOT NULL,
    number_of_periods INT NOT NULL,
    residual_value_type VARCHAR(24) NOT NULL DEFAULT 'FIXED_AMOUNT',
    residual_value DECIMAL(18,2) NOT NULL DEFAULT 0,
    depreciable_amount DECIMAL(18,2) NOT NULL,
    depreciation_per_period DECIMAL(18,2) NOT NULL,
    depreciation_expense_account VARCHAR(160),
    accumulated_depreciation_account VARCHAR(160),
    pro_rata_convention VARCHAR(32) NOT NULL DEFAULT 'FULL_MONTH',
    depreciate_in_purchase_month BOOLEAN NOT NULL DEFAULT TRUE,
    include_in_run BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    last_run_at DATETIME(6),
    next_run_date DATE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_depreciation_schedule_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    INDEX idx_depreciation_schedule (organization_id, status, next_run_date, deleted),
    INDEX idx_depreciation_asset (asset_id, start_date)
);

CREATE TABLE asset_depreciation_entries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    financial_year VARCHAR(16) NOT NULL,
    period_number INT NOT NULL,
    period_label VARCHAR(40) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    opening_book_value DECIMAL(18,2) NOT NULL,
    depreciation_amount DECIMAL(18,2) NOT NULL,
    accumulated_depreciation DECIMAL(18,2) NOT NULL,
    closing_book_value DECIMAL(18,2) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    posted_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_depreciation_entry_schedule FOREIGN KEY (schedule_id) REFERENCES asset_depreciation_schedules(id) ON DELETE CASCADE,
    CONSTRAINT fk_depreciation_entry_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT uk_depreciation_period UNIQUE (schedule_id, period_number),
    INDEX idx_depreciation_entry_asset (asset_id, start_date, status)
);

CREATE TABLE asset_disposals (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    disposal_number VARCHAR(48) NOT NULL,
    asset_id BIGINT NOT NULL,
    disposal_date DATE NOT NULL,
    disposal_method VARCHAR(32) NOT NULL,
    buyer_vendor_id BIGINT,
    buyer_vendor_name VARCHAR(180),
    reference_number VARCHAR(100),
    reason VARCHAR(255) NOT NULL,
    gain_loss_account VARCHAR(160),
    depreciation_method VARCHAR(32),
    accumulated_depreciation DECIMAL(18,2) NOT NULL DEFAULT 0,
    net_book_value DECIMAL(18,2) NOT NULL DEFAULT 0,
    disposal_value DECIMAL(18,2) NOT NULL DEFAULT 0,
    gain_loss_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    gain_loss_percentage DECIMAL(10,4) NOT NULL DEFAULT 0,
    remarks TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    approved_by VARCHAR(180),
    approved_at DATETIME(6),
    approval_notes TEXT,
    completed_at DATETIME(6),
    reversed_at DATETIME(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'Admin',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_disposal_number UNIQUE (organization_id, disposal_number),
    CONSTRAINT fk_disposal_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT fk_disposal_buyer FOREIGN KEY (buyer_vendor_id) REFERENCES vendors(id),
    INDEX idx_disposal_status (organization_id, status, disposal_date, deleted),
    INDEX idx_disposal_asset (asset_id, status)
);

CREATE TABLE asset_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    asset_id BIGINT NOT NULL,
    event_type VARCHAR(48) NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32),
    reference_type VARCHAR(48),
    reference_id BIGINT,
    description VARCHAR(1000) NOT NULL,
    actor VARCHAR(120) NOT NULL DEFAULT 'Admin',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_asset_history_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    INDEX idx_asset_history (asset_id, created_at),
    INDEX idx_asset_history_org (organization_id, event_type, created_at)
);

INSERT INTO asset_categories
    (organization_id, category_code, category_name, description, default_depreciation_method,
     useful_life_years, residual_value_percentage, depreciation_frequency, default_asset_condition,
     display_color, status)
VALUES
    (1, 'IT', 'IT Equipment', 'Computers, laptops, servers and related IT assets', 'STRAIGHT_LINE', 3, 5, 'MONTHLY', 'GOOD', '#2563eb', 'ACTIVE'),
    (1, 'FUR', 'Office Furniture', 'Desks, chairs, cabinets and office furniture', 'STRAIGHT_LINE', 10, 5, 'MONTHLY', 'GOOD', '#ef1f2c', 'ACTIVE'),
    (1, 'VEH', 'Vehicles', 'Company vehicles and transportation assets', 'WRITTEN_DOWN_VALUE', 5, 10, 'MONTHLY', 'GOOD', '#16a34a', 'ACTIVE'),
    (1, 'MCH', 'Machinery', 'Production and industrial machinery', 'WRITTEN_DOWN_VALUE', 10, 5, 'MONTHLY', 'GOOD', '#f97316', 'ACTIVE');
