CREATE TABLE fixed_cost_project_milestone (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    milestone_name VARCHAR(180) NOT NULL,
    description VARCHAR(1000) NULL,
    start_date DATE NULL,
    due_date DATE NOT NULL,
    amount DECIMAL(16,2) NOT NULL DEFAULT 0,
    weightage DECIMAL(7,2) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PLANNED',
    progress DECIMAL(7,2) NOT NULL DEFAULT 0,
    notes VARCHAR(2000) NULL,
    invoice_id BIGINT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_project_milestone_name UNIQUE (project_id, milestone_name),
    CONSTRAINT fk_milestone_project FOREIGN KEY (project_id) REFERENCES business_records(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_invoice FOREIGN KEY (invoice_id) REFERENCES business_records(id),
    INDEX idx_milestone_project_active (project_id, active),
    INDEX idx_milestone_due_date (due_date)
);
