CREATE TABLE e_invoice_details (
    id BIGINT NOT NULL AUTO_INCREMENT,
    invoice_id BIGINT NOT NULL,
    irn VARCHAR(128) NULL,
    ack_no VARCHAR(64) NULL,
    ack_date DATETIME(6) NULL,
    signed_invoice LONGTEXT NULL,
    signed_qr_code LONGTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NOT_GENERATED',
    irp_request LONGTEXT NULL,
    irp_response LONGTEXT NULL,
    generated_at DATETIME(6) NULL,
    cancelled_at DATETIME(6) NULL,
    cancel_reason VARCHAR(8) NULL,
    cancel_remarks VARCHAR(500) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(2000) NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    version BIGINT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_e_invoice_invoice UNIQUE (invoice_id),
    CONSTRAINT uk_e_invoice_irn UNIQUE (irn),
    CONSTRAINT fk_e_invoice_invoice FOREIGN KEY (invoice_id) REFERENCES business_records (id),
    INDEX idx_e_invoice_status (status),
    INDEX idx_e_invoice_ack_no (ack_no)
);

CREATE TABLE e_invoice_api_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    invoice_id BIGINT NULL,
    credit_note_id BIGINT NULL,
    api_type VARCHAR(40) NOT NULL,
    request_payload LONGTEXT NULL,
    response_payload LONGTEXT NULL,
    http_status INT NULL,
    success BIT(1) NOT NULL DEFAULT b'0',
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(2000) NULL,
    created_by BIGINT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_e_invoice_log_invoice FOREIGN KEY (invoice_id) REFERENCES business_records (id),
    CONSTRAINT fk_e_invoice_log_credit_note FOREIGN KEY (credit_note_id) REFERENCES business_records (id),
    INDEX idx_e_invoice_log_invoice (invoice_id, created_at),
    INDEX idx_e_invoice_log_credit_note (credit_note_id, created_at),
    INDEX idx_e_invoice_log_api_type (api_type, created_at)
);
