INSERT INTO business_records
(module, type, record_number, party_name, party_email, party_phone, party_city, category, status, secondary_status, amount, balance_amount, record_date, due_date, reference_number, payment_mode, owner_name, notes, created_at, updated_at)
VALUES
('resources','resources','EMP001','Hardeep Singh','hardeep@intelliatech.com','+91 90001 00001','Chennai, India','Project Manager','Active','Partially Available',92.00,0.00,'2024-05-30',NULL,'ICE Claim System','Fixed Cost','Arun Kumar','{"skills":["Java","Spring Boot","AWS","Agile"],"currentProject":"ICE Claim System","client":"IntelliSwift (Pty) Ltd.","resourceType":"Full Time","experience":"8 years"}',NOW(6),NOW(6)),
('resources','resources','EMP002','Arpit M.','arpit@intelliatech.com','+91 90001 00002','Bangalore, India','Backend Developer','Active','Full',85.00,0.00,'2024-05-30',NULL,'Application Maintenance','Staffing','Priya Sharma','{"skills":["Java","Microservices","PostgreSQL"],"currentProject":"Application Maintenance","client":"DataMatics","resourceType":"Full Time","experience":"6 years"}',NOW(6),NOW(6)),
('resources','resources','EMP003','Sumit','sumit@intelliatech.com','+91 90001 00003','Pune, India','Frontend Developer','Active','Partially Available',78.00,0.00,'2024-05-30',NULL,'LMS Platform','Fixed Cost','Nisha Verma','{"skills":["ReactJS","JavaScript","HTML"],"currentProject":"LMS Platform","client":"EduSmart","resourceType":"Full Time","experience":"5 years"}',NOW(6),NOW(6)),
('resources','resources','EMP004','Aadarsh','aadarsh@intelliatech.com','+91 90001 00004','Hyderabad, India','QA Engineer','Active','Full',70.00,0.00,'2024-05-30',NULL,'Cloud Support Services','Staffing','Rohit Singh','{"skills":["Manual Testing","Selenium","JIRA"],"currentProject":"Cloud Support Services","client":"CloudFirst Ltd.","resourceType":"Contract","experience":"4 years"}',NOW(6),NOW(6)),
('resources','resources','EMP005','Neha Joshi','neha@intelliatech.com','+91 90001 00005','Chennai, India','UI/UX Designer','Active','Full',65.00,0.00,'2024-05-30',NULL,'Mobile App Development','Fixed Cost','Arun Kumar','{"skills":["Figma","Adobe XD","UI Design"],"currentProject":"Mobile App Development","client":"HealthPlus","resourceType":"Full Time","experience":"5 years"}',NOW(6),NOW(6)),
('resources','resources','EMP006','Rahul Sharma','rahul@intelliatech.com','+91 90001 00006','Noida, India','DevOps Engineer','Active','Partially Available',88.00,0.00,'2024-05-30',NULL,'DevOps Managed Services','Staffing','Priya Sharma','{"skills":["AWS","Docker","Jenkins","Kubernetes"],"currentProject":"DevOps Managed Services","client":"InnoTech","resourceType":"Full Time","experience":"7 years"}',NOW(6),NOW(6)),
('resources','resources','EMP007','Pooja Verma','pooja@intelliatech.com','+91 90001 00007','Delhi, India','Business Analyst','Active','Full',60.00,0.00,'2024-05-30',NULL,'E-Commerce Platform','Fixed Cost','Nisha Verma','{"skills":["Requirement","JIRA","Confluence"],"currentProject":"E-Commerce Platform","client":"ShopEase","resourceType":"Full Time","experience":"6 years"}',NOW(6),NOW(6)),
('resources','resources','EMP008','Mayank Patel','mayank@intelliatech.com','+91 90001 00008','Ahmedabad, India','React Developer','Active','Partially Available',75.00,0.00,'2024-05-30',NULL,'Analytics Dashboard','Staffing','Rohit Singh','{"skills":["ReactJS","Redux","TypeScript"],"currentProject":"Analytics Dashboard","client":"FinSight","resourceType":"Contract","experience":"4 years"}',NOW(6),NOW(6)),
('resources','resources','EMP009','Sneha Iyer','sneha@intelliatech.com','+91 90001 00009','Mumbai, India','Data Engineer','Active','Available',0.00,0.00,'2024-05-30',NULL,'-','Staffing','Arun Kumar','{"skills":["Python","SQL","ETL"],"currentProject":"-","client":"-","resourceType":"Full Time","experience":"5 years"}',NOW(6),NOW(6)),
('resources','resources','EMP010','Rohit Gupta','rohit@intelliatech.com','+91 90001 00010','Indore, India','.NET Developer','Active','Available',0.00,0.00,'2024-05-30',NULL,'-','-','Priya Sharma','{"skills":["C#","ASP.NET","SQL Server"],"currentProject":"-","client":"-","resourceType":"Full Time","experience":"6 years"}',NOW(6),NOW(6));
